version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    networks:
      - app-network
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/ada_fastfood
    networks:
      - app-network
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: