name: Docker Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: phucan22/ada-fastfood-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Frontend  
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: phucan22/ada-fastfood-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max